language: php
php:
  - 7.1.9
before_install:
  - sudo apt-get update
  - sudo apt-get install libmemcached-dev
  - pecl install mongodb-1.4.0
  - echo "no --disable-memcached-sasl" | pecl install memcached-3.0.3
install: composer install
script:
  - vendor/bin/phpcs
  - vendor/bin/phpcpd Application
  - vendor/bin/phpunit --stop-on-failure
  - vendor/bin/phpmd ./Application text ruleset.xml
