#!/bin/sh

phpfpmContainerName='monkey-phpfpm'

if [ $(expr `cat VERSION` \> $(docker exec phpfpmContainerName sh -c "ls Docs/version/*.md | sort -rn | awk -F '\/' '{print $3}' | sed -n '1 s/.md//p'")) -ne 0 ]
then
	echo 'push fail, VERSION file different with latest version log'
	exit 1
fi

if [ $(expr `cat VERSION` \< $(docker exec phpfpmContainerName sh -c "ls Docs/version/*.md | sort -rn | awk -F '\/' '{print $3}' | sed -n '1 s/.md//p'")) -ne 0 ]
then
	echo 'push fail, VERSION file different with latest version log'
	exit 1
fi

echo 'push check version ok'
