#!/bin/bash

#全局变量
phpfpmContainerName='monkey-phpfpm'

#加载公共smart函数库
. ./smartfunc/smartfunc
#加载环境函数库
. ./smartfunc/environmentfunc
#加载phpfunc,php相关函数库
. ./smartfunc/phpfunc

case $1 in
'initial') 
	;;
'start')
	environmentStart
	;;
'stop')
	environmentStop
	;;
'upgrade')
	environmentUpgrade
	;;
'cbf')
	cbf $phpfpmContainerName
	;;
'composer')
	composer $phpfpmContainerName
	;;
'cs')
	cs $phpfpmContainerName
	;;
'cpd')
	cpd $phpfpmContainerName
	;;
'md')
	md $phpfpmContainerName
	;;
'unit')
	unit $phpfpmContainerName
	;;
'unitFile')
	unitFile $phpfpmContainerName $2
	;;
'unitCover')
	unitCover $phpfpmContainerName
	;;
*)
	menu
esac


